In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import json

In [11]:
cd /content/drive/My Drive/Yoga Pose Estimation

/content/drive/My Drive/Yoga Pose Estimation


In [12]:
dataset=pd.read_json('data.json')

In [13]:
dataset=dataset.transpose()

In [14]:
dataset

0           1           2   ...          31          32          33
0    183.633762  174.798109  192.000347  ...  539.227049  121.347420  442.948453
1    183.633762  174.798109  192.000347  ...  539.227049  121.347420  442.948453
2    184.904549  174.938407  192.566699  ...  537.403911  114.483648  436.303782
3    184.904549  174.938407  192.566699  ...  537.403911  114.483648  436.303782
4    184.538500  175.061510  191.929920  ...  536.079323  114.762792  437.779244
..          ...         ...         ...  ...         ...         ...         ...
595  185.402581  162.564516  194.571763  ...  504.171685  162.300425  504.483060
596  183.029738  175.337504  192.048168  ...  538.803738  121.505645  445.646148
597  183.029738  175.337504  192.048168  ...  538.803738  121.505645  445.646148
598  164.899034  181.075796  175.124130  ...  578.620245  141.716542  576.890510
599  164.899034  181.075796  175.124130  ...  578.620245  141.716542  576.890510

[600 rows x 34 columns]

In [15]:
labels=[]
for i in range(0,200):
  labels.append("a")
for i in range(0,200):
  labels.append("b")
for i in range(0,200):
  labels.append("c")


In [16]:
labels

['a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a'

In [17]:
train_feature,test_feature,label_train,label_test=train_test_split(dataset,labels,test_size=0.2,random_state=42)

In [18]:
train_feature

0           1           2   ...          31          32          33
145  177.612860  176.342468  188.891507  ...  538.344888  123.998024  448.980172
9    183.643985  175.810601  191.401392  ...  536.850129  116.398433  439.517794
375  183.633762  174.798109  192.000347  ...  539.227049  121.347420  442.948453
523  182.864026  175.169058  191.803203  ...  539.017696  122.851890  445.069055
188  184.441407  174.947741  191.841784  ...  537.703058  112.093199  436.378745
..          ...         ...         ...  ...         ...         ...         ...
71   177.230656  176.338776  188.712298  ...  538.862563  122.737017  448.443036
106  184.734741  175.355311  192.608477  ...  538.262095  113.444207  437.719615
270  184.359984  157.226726  192.980285  ...  502.935425  161.717924  501.395355
435  164.682124  181.738212  175.487421  ...  583.153427  138.529853  584.179600
102  183.820413  175.129558  191.884568  ...  538.563517  121.855426  444.452675

[480 rows x 34 columns]

In [35]:
from sklearn.model_selection import GridSearchCV
model=GridSearchCV(KNeighborsClassifier(),{'n_neighbors':list(np.arange(1,20))})


In [36]:
model.fit(train_feature,label_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [37]:
model.best_params_

{'n_neighbors': 1}

In [43]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(train_feature,label_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [44]:
label_pred=model.predict(test_feature)

In [48]:
label_pred=list(label_pred)

In [65]:
def counter(l):
  uniq=list(set(l))
  for i in uniq:
    print(i+" count is "+str(l.count(i)))

In [66]:
counter(label_pred)

c count is 33
a count is 47
b count is 40


In [67]:
counter(label_test)

c count is 41
a count is 43
b count is 36


In [46]:
from sklearn.metrics import *

In [47]:
accuracy_score(label_test,label_pred)

0.8

In [68]:
import pickle

In [69]:
pickle.dump(model,open('model.pkl','wb+'))

In [70]:
print(classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           a       0.83      0.91      0.87        43
           b       0.70      0.78      0.74        36
           c       0.88      0.71      0.78        41

    accuracy                           0.80       120
   macro avg       0.80      0.80      0.80       120
weighted avg       0.81      0.80      0.80       120



In [71]:
print(confusion_matrix(label_test,label_pred))

[[39  4  0]
 [ 4 28  4]
 [ 4  8 29]]
