In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import json

In [2]:
cd /content/drive/My Drive/Yoga Pose Estimation

/content/drive/My Drive/Yoga Pose Estimation


In [4]:
dataset=pd.read_json('data(3).json')

In [5]:
dataset=dataset.transpose()

In [6]:
dataset

0           1           2   ...          31          32          33
0     217.452016   97.740734  228.342174  ...  586.645860  137.374224  455.696359
1     217.452016   97.740734  228.342174  ...  586.645860  137.374224  455.696359
2     217.452016   97.740734  228.342174  ...  586.645860  137.374224  455.696359
3     217.452016   97.740734  228.342174  ...  586.645860  137.374224  455.696359
4     217.571389   97.117280  227.997406  ...  587.635184  139.343104  459.568907
...          ...         ...         ...  ...         ...         ...         ...
1195  164.565392  181.193815  175.721080  ...  579.613875  143.233756  578.220864
1196  164.565392  181.193815  175.721080  ...  579.613875  143.233756  578.220864
1197  213.507502   96.794710  224.077320  ...  588.358314  133.295808  439.834645
1198  187.515378  161.118362  197.117352  ...  504.811984  165.122877  503.477689
1199  187.515378  161.118362  197.117352  ...  504.811984  165.122877  503.477689

[1200 rows x 34 columns]

In [7]:
labels=[]
for i in range(0,400):
  labels.append("a")
for i in range(0,400):
  labels.append("b")
for i in range(0,400):
  labels.append("c")


In [8]:
labels

['a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a'

In [9]:
train_feature,test_feature,label_train,label_test=train_test_split(dataset,labels,test_size=0.2,random_state=42)

In [10]:
train_feature

0           1           2   ...          31          32          33
331   219.904456   99.804809  231.432312  ...  513.777402  139.534968  463.834697
409   215.059716   95.523372  225.657394  ...  582.654944  133.690829  440.489667
76    216.053742   99.095245  225.670683  ...  581.628037  137.145967  440.337549
868   164.988869  180.856275  176.056559  ...  579.382063  142.276305  576.957733
138   213.755724   96.082288  223.708866  ...  587.974841  139.079898  513.540245
...          ...         ...         ...  ...         ...         ...         ...
1044  205.877617   94.869971  220.010135  ...  582.263565  185.626227  507.930212
1095  164.457759  181.619869  174.214775  ...  578.535204  141.558052  577.783268
1130  187.515378  161.118362  197.117352  ...  504.811984  165.122877  503.477689
860   216.644882  101.153820  226.975009  ...  519.090467  156.010696  460.552349
1126  164.688103  182.677366  174.357385  ...  581.322616  139.311332  583.218122

[960 rows x 34 columns]

In [11]:
from sklearn.model_selection import GridSearchCV
model=GridSearchCV(KNeighborsClassifier(),{'n_neighbors':list(np.arange(1,20))})


In [12]:
model.fit(train_feature,label_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [13]:
model.best_params_

{'n_neighbors': 1}

In [14]:
model=KNeighborsClassifier(n_neighbors=1)
model.fit(train_feature,label_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [15]:
label_pred=model.predict(test_feature)

In [16]:
label_pred=list(label_pred)

In [17]:
def counter(l):
  uniq=list(set(l))
  for i in uniq:
    print(i+" count is "+str(l.count(i)))

In [18]:
counter(label_pred)

b count is 81
a count is 85
c count is 74


In [19]:
counter(label_test)

b count is 73
a count is 87
c count is 80


In [20]:
from sklearn.metrics import *

In [21]:
accuracy_score(label_test,label_pred)

0.9041666666666667

In [22]:
import pickle

In [23]:
pickle.dump(model,open('model_1200.pkl','wb+'))

In [24]:
print(classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           a       0.92      0.90      0.91        87
           b       0.85      0.95      0.90        73
           c       0.95      0.88      0.91        80

    accuracy                           0.90       240
   macro avg       0.91      0.91      0.90       240
weighted avg       0.91      0.90      0.90       240



In [25]:
print(confusion_matrix(label_test,label_pred))

[[78  6  3]
 [ 3 69  1]
 [ 4  6 70]]
